name: Elakka

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cp /home/abjs/githubDeploy/elakka/.env ./
    - run: pm2 flush      
    - run: npm i
    - run: pm2 restart price
    - run: pm2 save  
    
