name: Elakka

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Environment
      run : cat Abin/node-price/.env >> .env
    - name: Node Install     
      run : npm i
    - name: Python Environment
      run : cp ../../../config.py ./
    - name: Python Backup
      run : cp ../../../backup.py ./
    - name: Python Requirements
      run : python3 -m pip install -r requirements.txt
    - name: PM2 Resatart
      run : pm2 restart price

    
