name: Elakka

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cp /home/abjs/githubDeploy/elakka/.env ./      
    - run: npm i
    - run: cp /home/abjs/githubDeploy/elakka/config.py ./
    - run: python3 -m pip install -r requirements.txt
    - run: pm2 restart price

    
